In [1]:
import pandas as pd
from carsus.io.cmfgen import CMFGENEnergyLevelsParser, CMFGENOscillatorStrengthsParser
import numpy as np

 ChiantiPy version 0.8.4
 found PyQt5 widgets
 using PyQt5 widgets

In [2]:
# path = './Datasets/atomic/SIL/II/16sep15/'
name = 'si2_osc_kurucz'
# filename = path + name
filename = name

Using Carsus Inbuilt functions

In [3]:
si2_energy_levels = CMFGENEnergyLevelsParser(filename)

In [4]:
si2_energy_levels.base

,Configuration,g,E(cm^-1),10^15 Hz,eV,Lam(A),ID,ARAD,C4,C6
0,3s2_3p_2Po[1/2],2.0,0.00,3.95241,16.346,758.5,1,0.000000e+00,-5.290000e-17,7.470000e-33
1,3s2_3p_2Po[3/2],4.0,287.24,3.94380,16.310,760.2,2,0.000000e+00,-5.300000e-17,7.460000e-33
2,3s_3p2_4Pe[1/2],2.0,42824.29,2.66857,11.036,1123.0,3,1.222000e+04,-5.340000e-17,7.490000e-33
3,3s_3p2_4Pe[3/2],4.0,42932.62,2.66532,11.023,1125.0,4,2.110000e+03,-5.340000e-17,7.490000e-33
4,3s_3p2_4Pe[5/2],6.0,43107.91,2.66007,11.001,1127.0,5,3.246000e+03,-5.350000e-17,7.490000e-33
...,...,...,...,...,...,...,...,...,...,...
152,3s_3p(3Po)4p_4Pe[3/2],4.0,134079.00,-0.06718,-0.278,-44630.0,153,1.159000e+08,-1.500000e-16,3.080000e-32
153,3s_3p(3Po)4p_4Pe[5/2],6.0,134213.63,-0.07122,-0.295,-42100.0,154,1.167000e+08,-1.500000e-16,3.090000e-32
154,3s_3p(3Po)4p_4Se[3/2],4.0,134905.28,-0.09195,-0.380,-32600.0,155,9.275000e+07,-9.750000e-17,2.770000e-32
155,3p3_2Do[5/2],6.0,135297.30,-0.10370,-0.429,-28910.0,156,2.437000e+09,4.200000e-17,1.450000e-32
156,3p3_2Do[3/2],4.0,135303.50,-0.10389,-0.430,-28860.0,157,2.438000e+09,1.390000e-17,1.460000e-32

In [5]:
si2_osc_strengths = CMFGENOscillatorStrengthsParser(filename)

In [6]:
si2_osc_strengths.base

,State A,State B,f,A,Lam(A),i,j,Lam(obs),% Acc
0,3s2_3p_2Po[1/2],3s_3p2_4Pe[1/2],5.741000e-06,7.023000e+03,2335.123,1,3,NaN,NaN
1,3s2_3p_2Po[1/2],3s_3p2_4Pe[3/2],3.564000e-08,2.191000e+01,2329.231,1,4,NaN,NaN
2,3s2_3p_2Po[1/2],3s_3p2_2De[3/2],7.638000e-04,7.793000e+05,1808.013,1,6,NaN,NaN
3,3s2_3p_2Po[1/2],3s2_4s_2Se[1/2],1.279000e-01,3.661000e+08,1526.707,1,8,NaN,NaN
4,3s2_3p_2Po[1/2],3s_3p2_2Se[1/2],1.062000e-01,4.162000e+08,1304.370,1,9,NaN,NaN
...,...,...,...,...,...,...,...,...,...
4191,3s_3p(3Po)4p_4Pe[3/2],3p3_2Do[3/2],3.250000e-06,3.251000e+00,81665.986,153,157,NaN,NaN
4192,3s_3p(3Po)4p_4Pe[5/2],3p3_2Do[5/2],6.605000e-07,5.173000e-01,92279.015,154,156,NaN,NaN
4193,3s_3p(3Po)4p_4Pe[5/2],3p3_2Do[3/2],4.129000e-08,4.907000e-02,91754.062,154,157,NaN,NaN
4194,3s_3p(3Po)4p_4Se[3/2],3p3_2Do[5/2],7.673000e-06,5.243000e-01,255100.000,155,156,NaN,NaN
4195,3s_3p(3Po)4p_4Se[3/2],3p3_2Do[3/2],6.744000e-07,7.134000e-02,251100.000,155,157,NaN,NaN

In [7]:
si2_energy_levels.meta

{'Date': '16-Sep-2015',
 'Format date': '17-Jun-2014',
 'Number of energy levels': '157',
 'Ionization energy': '131838.1400',
 'Screened nuclear charge': '2.0',
 'Number of transitions': '4196'}

Self Implementation

In [8]:
# Opening the file
file =  open(filename, "r")

# Storing all lines as an array
lines = file.readlines()

# Close file
file.close()

In [9]:
# Reading meta data
meta_i, meta_j = 10, 16
meta_lines = lines[meta_i: meta_j]
meta_data = {}

for line in meta_lines:
    index = line.find("!")
    val, key = line[:index], line[index + 1:]
    flag = False
#     Removing excessive whitespace characters in val
    j = index
    for i in range(1, len(val)):
        if val[i] == val[i - 1] and val[i] == ' ':
            j = i - 1
            break
    val = val[:j]
#     Removing \n characters in key
    key = key[:-1]
#     Adding value in metadata dictionary
    meta_data[key] = val

meta_data

{'Format date': '17-Jun-2014',
 'Date': '16-Sep-2015',
 'Number of energy levels': '157',
 'Ionization energy': '131838.1400',
 'Screened nuclear charge': '2.0',
 'Number of transitions': '4196'}

In [10]:
cols = lines[7].split()

In [11]:
cols.insert(0, 'Configuration')

In [12]:
cols

['Configuration',
 'g',
 'E(cm^-1)',
 '10^15',
 'Hz',
 'eV',
 'Lam(A)',
 'ID',
 'ARAD',
 'C4',
 'C6']

In [13]:
cols.remove('Hz')
cols[3] += ' Hz'
cols

['Configuration',
 'g',
 'E(cm^-1)',
 '10^15 Hz',
 'eV',
 'Lam(A)',
 'ID',
 'ARAD',
 'C4',
 'C6']

In [14]:
# Reading Energy Levels
energy_i = 17
energy_j = energy_i + int(meta_data['Number of energy levels'])
energy_lines = lines[energy_i: energy_j]
energy_data = []

index = 0
for line in energy_lines:
    vals = line.split()
#     Converting strings to floats
    for i in range(1, len(vals)):
        vals[i] = float(vals[i])
    energy_data.append(vals)

energy_data = pd.DataFrame(data = energy_data, columns = cols)

In [15]:
energy_data

,Configuration,g,E(cm^-1),10^15 Hz,eV,Lam(A),ID,ARAD,C4,C6
0,3s2_3p_2Po[1/2],2.0,0.00,3.95241,16.346,758.5,1.0,0.000000e+00,-5.290000e-17,7.470000e-33
1,3s2_3p_2Po[3/2],4.0,287.24,3.94380,16.310,760.2,2.0,0.000000e+00,-5.300000e-17,7.460000e-33
2,3s_3p2_4Pe[1/2],2.0,42824.29,2.66857,11.036,1123.0,3.0,1.222000e+04,-5.340000e-17,7.490000e-33
3,3s_3p2_4Pe[3/2],4.0,42932.62,2.66532,11.023,1125.0,4.0,2.110000e+03,-5.340000e-17,7.490000e-33
4,3s_3p2_4Pe[5/2],6.0,43107.91,2.66007,11.001,1127.0,5.0,3.246000e+03,-5.350000e-17,7.490000e-33
...,...,...,...,...,...,...,...,...,...,...
152,3s_3p(3Po)4p_4Pe[3/2],4.0,134079.00,-0.06718,-0.278,-44630.0,153.0,1.159000e+08,-1.500000e-16,3.080000e-32
153,3s_3p(3Po)4p_4Pe[5/2],6.0,134213.63,-0.07122,-0.295,-42100.0,154.0,1.167000e+08,-1.500000e-16,3.090000e-32
154,3s_3p(3Po)4p_4Se[3/2],4.0,134905.28,-0.09195,-0.380,-32600.0,155.0,9.275000e+07,-9.750000e-17,2.770000e-32
155,3p3_2Do[5/2],6.0,135297.30,-0.10370,-0.429,-28910.0,156.0,2.437000e+09,4.200000e-17,1.450000e-32
156,3p3_2Do[3/2],4.0,135303.50,-0.10389,-0.430,-28860.0,157.0,2.438000e+09,1.390000e-17,1.460000e-32

In [16]:
cols2 = lines[184].split()
cols2

['Transition', 'f', 'A', 'Lam(A)', 'i-j', 'Lam(obs)', '%', 'Acc']

In [17]:
# Rectifying Columns
cols2.remove('%')
cols2[6] = '% ' + cols2[6]
cols2.insert(5, 'j')
cols2[4] = 'i'
cols2[0] = 'State A'
cols2.insert(1, 'State B')

In [18]:
cols2

['State A', 'State B', 'f', 'A', 'Lam(A)', 'i', 'j', 'Lam(obs)', '% Acc']

In [26]:
# Reading Oscillator Strengths
osc_i = 186
osc_j = osc_i + int(meta_data['Number of transitions'])
osc_lines = lines[osc_i: osc_j]
osc_data = []

index = 0
for line in osc_lines:
    vals = line.split()
#     To check if the two states are not combined
    flag = vals[0].find(']') + 1 == len(vals[0])
    if not flag:
        vals.insert(1, vals[0][vals[0].find(']') + 1:])
        vals[0] = vals[0][:vals[0].find(']') + 1]
        vals = vals[:-1]
    vals[1] = vals[1][1:]
    vals[5] = vals[5][:-1]
#     Converting strings to floats
    for i in range(2, len(vals)):
        try:
            vals[i] = float(vals[i])
        except ValueError:
            vals[i] =  np.nan
    vals = vals[:-1]
    osc_data.append(vals)

osc_data = pd.DataFrame(data = osc_data, columns = cols2)

In [27]:
osc_data

,State A,State B,f,A,Lam(A),i,j,Lam(obs),% Acc
0,3s2_3p_2Po[1/2],3s_3p2_4Pe[1/2],5.741000e-06,7.023000e+03,2335.123,1.0,3.0,NaN,NaN
1,3s2_3p_2Po[1/2],3s_3p2_4Pe[3/2],3.564000e-08,2.191000e+01,2329.231,1.0,4.0,NaN,NaN
2,3s2_3p_2Po[1/2],3s_3p2_2De[3/2],7.638000e-04,7.793000e+05,1808.013,1.0,6.0,NaN,NaN
3,3s2_3p_2Po[1/2],3s2_4s_2Se[1/2],1.279000e-01,3.661000e+08,1526.707,1.0,8.0,NaN,NaN
4,3s2_3p_2Po[1/2],3s_3p2_2Se[1/2],1.062000e-01,4.162000e+08,1304.370,1.0,9.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...
4191,3s_3p(3Po)4p_4Pe[3/2],3p3_2Do[3/2],3.250000e-06,3.251000e+00,81665.986,153.0,157.0,NaN,NaN
4192,3s_3p(3Po)4p_4Pe[5/2],3p3_2Do[5/2],6.605000e-07,5.173000e-01,92279.015,154.0,156.0,NaN,NaN
4193,3s_3p(3Po)4p_4Pe[5/2],3p3_2Do[3/2],4.129000e-08,4.907000e-02,91754.062,154.0,157.0,NaN,NaN
4194,3s_3p(3Po)4p_4Se[3/2],3p3_2Do[5/2],7.673000e-06,5.243000e-01,255100.000,155.0,156.0,NaN,NaN
4195,3s_3p(3Po)4p_4Se[3/2],3p3_2Do[3/2],6.744000e-07,7.134000e-02,251100.000,155.0,157.0,NaN,NaN